DROP ENDPOINT Mirroring;
GO

CREATE ENDPOINT Mirroring
STATE = STARTED
AS TCP (LISTENER_PORT = 5022)
FOR DATABASE_MIRRORING (
	AUTHENTICATION = WINDOWS NEGOTIATE,
	ENCRYPTION = REQUIRED ALGORITHM AES,
    ROLE = PARTNER
);

CREATE LOGIN [NT AUTHORITY\NETWORK SERVICE] FROM WINDOWS;
GRANT CONNECT ON ENDPOINT::Mirroring TO [NT AUTHORITY\NETWORK SERVICE]

ALTER DATABASE MainDB
SET PARTNER FAILOVER;

SELECT 
    name AS EndpointName,
    state_desc AS EndpointState,
    type_desc AS EndpointType,
    protocol_desc AS Protocol
FROM sys.endpoints
WHERE type_desc = 'DATABASE_MIRRORING';

